from datetime import timedelta


song_list = {
    "Be OK": timedelta(minutes=4, seconds=13),
    "Ever Green": timedelta(minutes=3, seconds=43),
    "Key": timedelta(minutes=3, seconds=40),
    "Bye My Tears": timedelta(minutes=3, seconds=12),
    "Knockin' on Your Heart": timedelta(minutes=3, seconds=52),
    "Big Dad": timedelta(minutes=3, seconds=26),
    "Before Dawn": timedelta(minutes=3, seconds=29),
    "Forward": timedelta(minutes=4, seconds=49),
    "Love Passion Matador": timedelta(minutes=3, seconds=18),
    "Summer Drive": timedelta(minutes=4, seconds=24),
    "Thrill": timedelta(minutes=4, seconds=4),
    "Freezer": timedelta(minutes=3, seconds=15),
    "Real Existence": timedelta(minutes=4, seconds=11),
    "Price of Pride": timedelta(minutes=3, seconds=27),
    "Arcadia Girl": timedelta(minutes=4, seconds=4),
    "Don't Apply the Brake": timedelta(minutes=3, seconds=19),
    "Beauty and the Beast": timedelta(minutes=3, seconds=3),
    "Don't Let Me Down": timedelta(minutes=3, seconds=19),
    "Shake That!": timedelta(minutes=4, seconds=5),
    "The Non-Fiction Days": timedelta(minutes=4, seconds=44),
    "Look at Me": timedelta(minutes=4, seconds=0),
    "Order": timedelta(minutes=3, seconds=24),
    "Brand-New Road": timedelta(minutes=3, seconds=55),
    "Yuragu": timedelta(minutes=4, seconds=5),
    "Freedom": timedelta(minutes=3, seconds=46),
    "Before Yesterday": timedelta(minutes=3, seconds=47),
    "Alone": timedelta(minutes=3, seconds=28),
    "Don't You Tell Me": timedelta(minutes=3, seconds=10),
    "Puzzle": timedelta(minutes=4, seconds=19),
    "Moratorium": timedelta(minutes=4, seconds=15),
    "YOLO": timedelta(minutes=4, seconds=25),
    "Cross": timedelta(minutes=3, seconds=45),
    "OOPArts": timedelta(minutes=4, seconds=6),
    "Take Me Higher!": timedelta(minutes=3, seconds=18),
    "So What?": timedelta(minutes=4, seconds=48),
    "Time": timedelta(minutes=3, seconds=29),
    "You.": timedelta(minutes=3, seconds=43),
    "Awkward": timedelta(minutes=3, seconds=32),
    "Decided by Myself": timedelta(minutes=3, seconds=54),
    "Secret My Lips": timedelta(minutes=4, seconds=11),
    "I Can't Live Without You": timedelta(minutes=3, seconds=49),
    "Play": timedelta(minutes=3, seconds=19),
    "One and Only": timedelta(minutes=3, seconds=22),
    "Domination": timedelta(minutes=3, seconds=51),
    "Fate": timedelta(minutes=4, seconds=31),
    "Spirit": timedelta(minutes=3, seconds=41),
    "Rock in Me": timedelta(minutes=3, seconds=21),
    "Clang": timedelta(minutes=4, seconds=10),
    "Turn Me On": timedelta(minutes=4, seconds=15),
    "Carry On Living": timedelta(minutes=3, seconds=32),
    "Daydreaming": timedelta(minutes=3, seconds=57),
    "Anemone": timedelta(minutes=4, seconds=22),
    "Alive-or-Dead": timedelta(minutes=3, seconds=44),
    "Dice": timedelta(minutes=4, seconds=2),
    "Page": timedelta(minutes=4, seconds=17),
    "Glory": timedelta(minutes=3, seconds=39),
    "Liberal": timedelta(minutes=3, seconds=14),
    "Endless Story": timedelta(minutes=3, seconds=44),
    "Mirage": timedelta(minutes=3, seconds=57),
    "At the Drop of a Hat": timedelta(minutes=4, seconds=19),
    "Wonderland": timedelta(minutes=3, seconds=55),
    "Azure": timedelta(minutes=2, seconds=49),
    "Dilemma": timedelta(minutes=3, seconds=36),
    "Bubble": timedelta(minutes=3, seconds=46),
    "The Dragon Cries": timedelta(minutes=3, seconds=55),
    "Flying High": timedelta(minutes=3, seconds=42),
    "Catharsis": timedelta(minutes=3, seconds=18),
    "Blooming": timedelta(minutes=3, seconds=49),
    "Rinne": timedelta(minutes=3, seconds=27),
    "Warning": timedelta(minutes=4, seconds=20),
    "No God": timedelta(minutes=4, seconds=10),
    "After Life": timedelta(minutes=3, seconds=23),
    "Manners": timedelta(minutes=3, seconds=50),
    "I Still Seek Revenge": timedelta(minutes=3, seconds=2),
    "H-G-K": timedelta(minutes=3, seconds=7),
    "Sayonakidori": timedelta(minutes=4, seconds=33),
    "Why Why Why": timedelta(minutes=3, seconds=37),
    "Chemical Reaction": timedelta(minutes=4, seconds=9),
    "Giovanni": timedelta(minutes=4, seconds=17),
    "Honkai": timedelta(minutes=3, seconds=16),
    "Black Hole": timedelta(minutes=3, seconds=5),
    "Unfair Game": timedelta(minutes=3, seconds=30),
    "Matchless Gum": timedelta(minutes=3, seconds=11),
    "YOLO (Instrumental)": timedelta(minutes=4, seconds=25),
    "Choose Me": timedelta(minutes=3, seconds=41),
    "Start Over": timedelta(minutes=3, seconds=15),
    "Screaming": timedelta(minutes=3, seconds=47),
    "Hide-and-Seek": timedelta(minutes=3, seconds=1),
    "Smile": timedelta(minutes=3, seconds=57),
    "Different": timedelta(minutes=3, seconds=33),
    "Don't Be Long": timedelta(minutes=3, seconds=19),
    "Sense": timedelta(minutes=3, seconds=24),
    "Hibana": timedelta(minutes=3, seconds=40),
    "Corallium": timedelta(minutes=3, seconds=55),
    "Onset": timedelta(minutes=3, seconds=59),
    "Without Holding Back": timedelta(minutes=3, seconds=33),
    "secret MAIKO lips": timedelta(minutes=4, seconds=24),
    "GIONCHO": timedelta(minutes=3, seconds=54),
    "Screaming (MAIKO)": timedelta(minutes=3, seconds=54),
    "TORA and TORA": timedelta(minutes=3, seconds=26),
    "ansan": timedelta(minutes=4, seconds=28),
    "Domination (Instrumental)": timedelta(minutes=3, seconds=51),
    "Dice (Instrumental)": timedelta(minutes=4, seconds=2),
    "After Life (Instrumental)": timedelta(minutes=3, seconds=23),
    "No God (Instrumental)": timedelta(minutes=4, seconds=10),
    "Giovanni (Instrumental)": timedelta(minutes=4, seconds=17),
    "Peace&Love": timedelta(minutes=3, seconds=10),
    "Flapping wings": timedelta(minutes=4, seconds=8)
}
